receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: "apps"
          metrics_path: /metrics
          static_configs:
            - targets: ["app1:8080"]
        - job_name: "otel-collector"
          static_configs:
            - targets: ["otel-collector:8889"]
  filelog:
    include: [ /var/log/app/*.json ]
    start_at: beginning
    operators:
      - type: json_parser
        parse_from: body
      - type: severity_parser
        parse_from: attributes.level
        mapping:
          debug: debug
          info: info
          warn: warn
          warning: warn
          error: error
      - type: add
        field: resource.service.name
        value: local-app

processors:
  batch: {}
  resource:
    attributes:
      - key: env
        value: local
        action: upsert

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls: { insecure: true }
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8889
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch, resource]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp, filelog]
      processors: [batch, resource]
      exporters: [loki]
