global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  # Tenta por nome de serviço (rede Docker) e, em paralelo, via host publish.
  # O primeiro que responder ficará UP.
  - job_name: otel-collector
    scrape_interval: 15s
    static_configs:
      - targets:
          - "otel-collector:8889"